-- DROP TABLE contact;
CREATE TABLE contact(
    id SERIAL PRIMARY KEY,
    email VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(50) NOT NULL,
    reason VARCHAR(350) NOT NULL,
    sent_date TIMESTAMPTZ NOT NULL
)